### ISSUE TITLE
Usage of `targetObject` is deprecated. Please use `target` instead.

### ISSUE THREAD

**Issue by gbrlmrllo** [funnelcloudinc/ember-cli-echarts#6]
Hi guys, congrats, this is an excellent addon. 👍 

Currently a deprecation warning is displayed, it would be great if it disappeared.

**Comment by cmackenz** [comment]
thanks for the heads up @gbrlmrllo! If you'd like to cut a PR I can get that merged in for you.

**Comment by rrodrigu3z** [comment]
Hi guys! great add-on :)
@cmackenz the PR opened by @gbrlmrllo seems to solve the warnings.

**Comment by cmackenz** [comment]
Sorry for the delay... This has been merged and published to npm (v 0.1.8).
